import { jsPDF } from 'jspdf'

export function generateInvoicePDF(inv, settings = {}) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const brandColor = settings.brandColor || '#a98252'
  const businessName = settings.businessName || 'Freelancer'
  const email = settings.email || ''

  const hexToRgb = (hex) => {
    const r = parseInt(hex.slice(1, 3), 16)
    const g = parseInt(hex.slice(3, 5), 16)
    const b = parseInt(hex.slice(5, 7), 16)
    return [r, g, b]
  }
  const [br, bg, bb] = hexToRgb(brandColor)

  // Header bar
  doc.setFillColor(br, bg, bb)
  doc.rect(0, 0, 210, 28, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text(businessName, 14, 18)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  if (email) doc.text(email, 14, 24)

  // Invoice label
  doc.setTextColor(br, bg, bb)
  doc.setFontSize(26)
  doc.setFont('helvetica', 'bold')
  doc.text('INVOICE', 196, 18, { align: 'right' })

  // Invoice meta
  doc.setTextColor(40, 40, 40)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  const meta = [
    ['Invoice #', inv.id],
    ['Date', new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })],
    ['Due date', inv.due || '—'],
    ['Status', (inv.status || '').toUpperCase()],
  ]
  let metaY = 38
  meta.forEach(([label, val]) => {
    doc.setFont('helvetica', 'bold')
    doc.text(label, 130, metaY)
    doc.setFont('helvetica', 'normal')
    doc.text(String(val), 196, metaY, { align: 'right' })
    metaY += 7
  })

  // Bill to
  doc.setFillColor(248, 248, 248)
  doc.rect(14, 36, 90, 34, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  doc.setTextColor(120, 120, 120)
  doc.text('BILL TO', 18, 43)
  doc.setFontSize(11)
  doc.setTextColor(20, 20, 20)
  doc.text(inv.client || '—', 18, 51)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(80, 80, 80)
  if (inv.project) doc.text(inv.project, 18, 58)
  if (inv.clientEmail) doc.text(inv.clientEmail, 18, 64)

  // Table header
  const tableY = 82
  doc.setFillColor(br, bg, bb)
  doc.rect(14, tableY, 182, 9, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.text('Description', 18, tableY + 6)
  doc.text('Amount', 196, tableY + 6, { align: 'right' })

  // Table row
  const rowY = tableY + 9
  doc.setFillColor(255, 255, 255)
  doc.rect(14, rowY, 182, 10, 'F')
  doc.setTextColor(30, 30, 30)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.text(inv.project || 'Services', 18, rowY + 7)
  doc.text(`€${Number(inv.amount || 0).toFixed(2)}`, 196, rowY + 7, { align: 'right' })

  // Subtotals
  let subY = rowY + 20
  const discounted = Number(inv.amount || 0) * (1 - (Number(inv.discount) || 0) / 100)
  const net = discounted * (1 + (Number(inv.tax) || 0) / 100)

  const addLine = (label, value, bold = false) => {
    doc.setFont('helvetica', bold ? 'bold' : 'normal')
    doc.setFontSize(10)
    doc.setTextColor(60, 60, 60)
    doc.text(label, 140, subY)
    doc.text(value, 196, subY, { align: 'right' })
    subY += 7
  }

  doc.setDrawColor(220, 220, 220)
  doc.line(130, subY - 4, 196, subY - 4)
  addLine('Subtotal', `€${Number(inv.amount || 0).toFixed(2)}`)
  if (inv.discount > 0) addLine(`Discount (${inv.discount}%)`, `-€${(Number(inv.amount || 0) * (inv.discount / 100)).toFixed(2)}`)
  if (inv.tax > 0) addLine(`IVA / VAT (${inv.tax}%)`, `€${(discounted * (inv.tax / 100)).toFixed(2)}`)
  doc.line(130, subY - 2, 196, subY - 2)
  doc.setFillColor(br, bg, bb)
  doc.rect(130, subY, 66, 10, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.text('TOTAL', 134, subY + 7)
  doc.text(`€${net.toFixed(2)}`, 196, subY + 7, { align: 'right' })

  // Notes
  if (inv.notes) {
    subY += 22
    doc.setTextColor(80, 80, 80)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    doc.text('Notes', 14, subY)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.text(inv.notes, 14, subY + 6)
  }

  // Payment link
  if (inv.paymentUrl) {
    subY += 18
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    doc.setTextColor(br, bg, bb)
    doc.text('Pay online:', 14, subY)
    doc.setFont('helvetica', 'normal')
    doc.text(inv.paymentUrl, 40, subY)
  }

  // Footer
  doc.setFillColor(245, 245, 245)
  doc.rect(0, 275, 210, 22, 'F')
  doc.setTextColor(140, 140, 140)
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.text(`Generated by ${businessName} · ${new Date().toLocaleDateString()}`, 105, 285, { align: 'center' })

  return doc
}

export function generateContractPDF(contract, settings = {}) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const brandColor = settings.brandColor || '#a98252'
  const businessName = settings.businessName || 'Freelancer'

  const hexToRgb = (hex) => {
    const r = parseInt(hex.slice(1, 3), 16)
    const g = parseInt(hex.slice(3, 5), 16)
    const b = parseInt(hex.slice(5, 7), 16)
    return [r, g, b]
  }
  const [br, bg, bb] = hexToRgb(brandColor)

  // Header
  doc.setFillColor(br, bg, bb)
  doc.rect(0, 0, 210, 28, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text(businessName, 14, 18)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text('SERVICE AGREEMENT', 196, 18, { align: 'right' })

  // Meta
  doc.setTextColor(40, 40, 40)
  doc.setFontSize(10)
  let y = 38
  const pairs = [
    ['Project', contract.project || '—'],
    ['Client', contract.client || '—'],
    ['Value', contract.value || '—'],
    ['Date', contract.date || new Date().toLocaleDateString('en-GB')],
  ]
  pairs.forEach(([label, val]) => {
    doc.setFont('helvetica', 'bold')
    doc.text(label + ':', 14, y)
    doc.setFont('helvetica', 'normal')
    doc.text(String(val), 50, y)
    y += 7
  })

  // Contract body
  y += 6
  doc.setDrawColor(br, bg, bb)
  doc.setLineWidth(0.5)
  doc.line(14, y, 196, y)
  y += 8

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(40, 40, 40)

  const content = contract.content || ''
  const lines = doc.splitTextToSize(content, 178)
  const pageHeight = 270
  lines.forEach(line => {
    if (y > pageHeight) {
      doc.addPage()
      y = 20
    }
    doc.text(line, 14, y)
    y += 5.5
  })

  // Signature block
  if (contract.status === 'signed') {
    y += 12
    if (y > 240) { doc.addPage(); y = 20 }
    doc.setFillColor(240, 255, 240)
    doc.rect(14, y, 182, 36, 'F')
    doc.setDrawColor(34, 197, 94)
    doc.rect(14, y, 182, 36, 'S')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(10)
    doc.setTextColor(20, 120, 50)
    doc.text('✓ ELECTRONICALLY SIGNED', 18, y + 9)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.setTextColor(40, 40, 40)
    if (contract.signer_name) doc.text(`Signed by: ${contract.signer_name}`, 18, y + 18)
    if (contract.signed_at) doc.text(`Date: ${new Date(contract.signed_at).toLocaleString()}`, 18, y + 25)
    doc.text('This electronic signature is legally binding.', 18, y + 32)
  }

  // Footer
  doc.setFillColor(245, 245, 245)
  doc.rect(0, 275, 210, 22, 'F')
  doc.setTextColor(140, 140, 140)
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.text(`${businessName} · Generated ${new Date().toLocaleDateString()}`, 105, 285, { align: 'center' })

  return doc
}
